### PR TITLE
[FEAT] Add style on the page

### PR DESCRIPTION
**Pull request by csouchet**
CodeSandbox logoCodeSandbox logo&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/assynour/icpm-demo-2022/add_style_on_the_page?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=assynour&repo=icpm-demo-2022&branch=add_style_on_the_page">VS Code</a>

image

image

### CODE REVIEW

**Comment by assynour** [comment]
Do you think we need to update the buttons' style on window resize?
style

**Comment by csouchet** [comment]
> Do you think we need to update the buttons' style on window resize?
> 
> style

I can do it 😉

**Comment by csouchet** [comment]
@assynour It's done 🙂 

image

**Comment by assynour** [comment]
Thank you!

**Pull request merged**
